import type { Metadata } from "next";
import { Wix_Madefor_Text } from "next/font/google";
import Header from "@/components/header/Header";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";

const WixSans = Wix_Madefor_Text({
  variable: "--font-wix",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${WixSans.variable} antialiased`}>
        <ReactQueryProvider>
          <Header />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
