import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/header/Header";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import Footer from "@/components/footer/Footer";

export const wixMadefor = localFont({
  src: [
    {
      path: "../assets/fonts/WixMadeforText-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/WixMadeforText-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/WixMadeforText-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-wix",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${wixMadefor.variable}`} lang="en">
      <body className="antialiased">
        <ReactQueryProvider>
          <Header />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
